### ISSUE TITLE
Replacing MachineConfig with ImageContentSourcePolicy to configure OCP registry mirror

### ISSUE THREAD

**Issue by manosnoam** [redhat-openshift/acm-submariner-tester#22]
Hi @SteveMattar 
Looking at the MachineConfig we're creating on **_every OCP node_**, in order to configure mirroring from internal registry to external images: 
https://github.com/redhat-openshift/acm-submariner-tester/blob/8bd34177193cfac20670c2ff623c598ab5a28f7f/setup_subm.sh#L3199-L3215

Which also includes the config source mirror data:
https://github.com/redhat-openshift/acm-submariner-tester/blob/8bd34177193cfac20670c2ff623c598ab5a28f7f/setup_subm.sh#L3100-L3180

Now I'm curious to know if it can be replaced with a simpler method as @MaxBab suggested - to apply an `image-content-source-policy.yaml `on the cluster, which does not require the long and risky nodes restarts process:

```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: brew-registry
spec:
  repositoryDigestMirrors:
  - mirrors:
    - "$BREW_REGISTRY"
    source: registry.redhat.io
  - mirrors:
    - "$BREW_REGISTRY"
    source: registry.stage.redhat.io
  - mirrors:
    - "$BREW_REGISTRY"
source: registry-proxy.engineering.redhat.com
```

A side note question - Will it work also if using 'SubCtl' deploy & join commands (without ACM and Submariner Addon) ?
